"use strict";
const firebase = require("../../db");
const firestore = firebase.firestore();

const updateLegalContent = async (req, res, next) => {
    try {
        const data = req.body;
        const legalContent = await firestore.collection("legal-content").doc('SMak8RPCdYsA2sqRqeU1');
        await legalContent.update(data);
        res.send({ status: "active", data: "Content updated successfully" });
    } catch (error) {
        res.status(400).send({ status: "inactive", data: error.message });
    }
};

const resetLegalContent = async (req, res, next) => {
    try {
        const data = {
            termsAndCondition:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac lorem vitae tincidunt. In tempor porttitor risus erat sed egestas malesuada sapien. Egestas a aliquet lorem eu auctor. Fermentum, sodales et ut ullamcorper proin convallis. Magna nulla gravida eu urna nisl, ornare nibh.Semper sollicitudin rutrum pharetra malesuada aliquet tellus libero. Interdum orci eu facilisis pharetra ullamcorper. Pulvinar tortor vitae ultrices id. Nulla in adipiscing tincidunt aliquet molestie bibendum. Nibh aenean sit faucibus vel. Suspendisse vel, tempus, pellentesque massa ut ipsum. Enim mauris libero volutpat pellentesque proin ac accumsan, a. Malesuada tellus velit aliquet ac senectus elit aliquam convallis sodales. Amet vestibulum vel quis ligula bibendum diam facilisi enim.Porttitor est risus et enim tortor, ornare venenatis. Scelerisque id habitasse lobortis ullamcorper feugiat ultricies. Aliquam ac mauris orci, lobortis mi porta. Leo a amet, lectus egestas ac egestas semper. Ut proin sem porta velit non et. Tempus magna nunc, metus vulputate fusce. Placerat dui dictumst suspendisse id. Fusce sodales bibendum aenean pellentesque et, felis mattis. Sed mauris, nisl, malesuada pellentesque commodo morbi eleifend. Vestibulum dui ut suspendisse sociis at ultrices. Neque, tempus, ut nullam sociis potenti. Sit risus imperdiet enim mattis convallis facilisis ullamcorper neque. Libero rhoncus ac faucibus sit massa hac. Arcu amet, lacus praesent mauris pellentesque. Nulla ipsum vitae leo quis auctor. Sit fames in id diam fringilla.Risus, malesuada urna sed amet adipiscing tristique. Mattis ridiculus maecenas volutpat venenatis, commodo sed nunc vel. Adipiscing viverra mauris pretium suspendisse bibendum ac in quis.',
            privacyPolicy:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac lorem vitae tincidunt. In tempor porttitor risus erat sed egestas malesuada sapien. Egestas a aliquet lorem eu auctor. Fermentum, sodales et ut ullamcorper proin convallis. Magna nulla gravida eu urna nisl, ornare nibh.Semper sollicitudin rutrum pharetra malesuada aliquet tellus libero. Interdum orci eu facilisis pharetra ullamcorper. Pulvinar tortor vitae ultrices id. Nulla in adipiscing tincidunt aliquet molestie bibendum. Nibh aenean sit faucibus vel. Suspendisse vel, tempus, pellentesque massa ut ipsum. Enim mauris libero volutpat pellentesque proin ac accumsan, a. Malesuada tellus velit aliquet ac senectus elit aliquam convallis sodales. Amet vestibulum vel quis ligula bibendum diam facilisi enim.Porttitor est risus et enim tortor, ornare venenatis. Scelerisque id habitasse lobortis ullamcorper feugiat ultricies. Aliquam ac mauris orci, lobortis mi porta. Leo a amet, lectus egestas ac egestas semper. Ut proin sem porta velit non et. Tempus magna nunc, metus vulputate fusce. Placerat dui dictumst suspendisse id. Fusce sodales bibendum aenean pellentesque et, felis mattis. Sed mauris, nisl, malesuada pellentesque commodo morbi eleifend. Vestibulum dui ut suspendisse sociis at ultrices. Neque, tempus, ut nullam sociis potenti. Sit risus imperdiet enim mattis convallis facilisis ullamcorper neque. Libero rhoncus ac faucibus sit massa hac. Arcu amet, lacus praesent mauris pellentesque. Nulla ipsum vitae leo quis auctor. Sit fames in id diam fringilla.Risus, malesuada urna sed amet adipiscing tristique. Mattis ridiculus maecenas volutpat venenatis, commodo sed nunc vel. Adipiscing viverra mauris pretium suspendisse bibendum ac in quis.',
            dataProtection:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac lorem vitae tincidunt. In tempor porttitor risus erat sed egestas malesuada sapien. Egestas a aliquet lorem eu auctor. Fermentum, sodales et ut ullamcorper proin convallis. Magna nulla gravida eu urna nisl, ornare nibh.Semper sollicitudin rutrum pharetra malesuada aliquet tellus libero. Interdum orci eu facilisis pharetra ullamcorper. Pulvinar tortor vitae ultrices id. Nulla in adipiscing tincidunt aliquet molestie bibendum. Nibh aenean sit faucibus vel. Suspendisse vel, tempus, pellentesque massa ut ipsum. Enim mauris libero volutpat pellentesque proin ac accumsan, a. Malesuada tellus velit aliquet ac senectus elit aliquam convallis sodales. Amet vestibulum vel quis ligula bibendum diam facilisi enim.Porttitor est risus et enim tortor, ornare venenatis. Scelerisque id habitasse lobortis ullamcorper feugiat ultricies. Aliquam ac mauris orci, lobortis mi porta. Leo a amet, lectus egestas ac egestas semper. Ut proin sem porta velit non et. Tempus magna nunc, metus vulputate fusce. Placerat dui dictumst suspendisse id. Fusce sodales bibendum aenean pellentesque et, felis mattis. Sed mauris, nisl, malesuada pellentesque commodo morbi eleifend. Vestibulum dui ut suspendisse sociis at ultrices. Neque, tempus, ut nullam sociis potenti. Sit risus imperdiet enim mattis convallis facilisis ullamcorper neque. Libero rhoncus ac faucibus sit massa hac. Arcu amet, lacus praesent mauris pellentesque. Nulla ipsum vitae leo quis auctor. Sit fames in id diam fringilla.Risus, malesuada urna sed amet adipiscing tristique. Mattis ridiculus maecenas volutpat venenatis, commodo sed nunc vel. Adipiscing viverra mauris pretium suspendisse bibendum ac in quis.',
            cookiePolicy:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac lorem vitae tincidunt. In tempor porttitor risus erat sed egestas malesuada sapien. Egestas a aliquet lorem eu auctor. Fermentum, sodales et ut ullamcorper proin convallis. Magna nulla gravida eu urna nisl, ornare nibh.Semper sollicitudin rutrum pharetra malesuada aliquet tellus libero. Interdum orci eu facilisis pharetra ullamcorper. Pulvinar tortor vitae ultrices id. Nulla in adipiscing tincidunt aliquet molestie bibendum. Nibh aenean sit faucibus vel. Suspendisse vel, tempus, pellentesque massa ut ipsum. Enim mauris libero volutpat pellentesque proin ac accumsan, a. Malesuada tellus velit aliquet ac senectus elit aliquam convallis sodales. Amet vestibulum vel quis ligula bibendum diam facilisi enim.Porttitor est risus et enim tortor, ornare venenatis. Scelerisque id habitasse lobortis ullamcorper feugiat ultricies. Aliquam ac mauris orci, lobortis mi porta. Leo a amet, lectus egestas ac egestas semper. Ut proin sem porta velit non et. Tempus magna nunc, metus vulputate fusce. Placerat dui dictumst suspendisse id. Fusce sodales bibendum aenean pellentesque et, felis mattis. Sed mauris, nisl, malesuada pellentesque commodo morbi eleifend. Vestibulum dui ut suspendisse sociis at ultrices. Neque, tempus, ut nullam sociis potenti. Sit risus imperdiet enim mattis convallis facilisis ullamcorper neque. Libero rhoncus ac faucibus sit massa hac. Arcu amet, lacus praesent mauris pellentesque. Nulla ipsum vitae leo quis auctor. Sit fames in id diam fringilla.Risus, malesuada urna sed amet adipiscing tristique. Mattis ridiculus maecenas volutpat venenatis, commodo sed nunc vel. Adipiscing viverra mauris pretium suspendisse bibendum ac in quis.',
            reportIncident:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac lorem vitae tincidunt. In tempor porttitor risus erat sed egestas malesuada sapien. Egestas a aliquet lorem eu auctor. Fermentum, sodales et ut ullamcorper proin convallis. Magna nulla gravida eu urna nisl, ornare nibh.Semper sollicitudin rutrum pharetra malesuada aliquet tellus libero. Interdum orci eu facilisis pharetra ullamcorper. Pulvinar tortor vitae ultrices id. Nulla in adipiscing tincidunt aliquet molestie bibendum. Nibh aenean sit faucibus vel. Suspendisse vel, tempus, pellentesque massa ut ipsum. Enim mauris libero volutpat pellentesque proin ac accumsan, a. Malesuada tellus velit aliquet ac senectus elit aliquam convallis sodales. Amet vestibulum vel quis ligula bibendum diam facilisi enim.Porttitor est risus et enim tortor, ornare venenatis. Scelerisque id habitasse lobortis ullamcorper feugiat ultricies. Aliquam ac mauris orci, lobortis mi porta. Leo a amet, lectus egestas ac egestas semper. Ut proin sem porta velit non et. Tempus magna nunc, metus vulputate fusce. Placerat dui dictumst suspendisse id. Fusce sodales bibendum aenean pellentesque et, felis mattis. Sed mauris, nisl, malesuada pellentesque commodo morbi eleifend. Vestibulum dui ut suspendisse sociis at ultrices. Neque, tempus, ut nullam sociis potenti. Sit risus imperdiet enim mattis convallis facilisis ullamcorper neque. Libero rhoncus ac faucibus sit massa hac. Arcu amet, lacus praesent mauris pellentesque. Nulla ipsum vitae leo quis auctor. Sit fames in id diam fringilla.Risus, malesuada urna sed amet adipiscing tristique. Mattis ridiculus maecenas volutpat venenatis, commodo sed nunc vel. Adipiscing viverra mauris pretium suspendisse bibendum ac in quis.',
        };
        await firestore.collection("legal-content").doc('SMak8RPCdYsA2sqRqeU1').update(data);
        res.send({ status: "active", data: "Content Reset successfully" });
    } catch (error) {
        res.status(400).send({ status: "inactive", data: error.message });
    }
};

const getLegalContent = async (req, res) => {
    try {
        const legalContent = await firestore.collection("legal-content").doc('SMak8RPCdYsA2sqRqeU1').get().then(snapshot => {
            if(snapshot.data()!==null && snapshot.data()!==undefined){
                res.send({ status: "active", "data": snapshot.data()})
            }else{
                res.status(404).send({ status: "inactive", message: 'Nothing Found' });
            }

        });
    } catch (error) {
        res.status(400).send({ status: "inactive", data: error.message });
    }
}

module.exports = {
    updateLegalContent,
    resetLegalContent,
    getLegalContent
};
